/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package projeto_fabricante_equipamento.n.GUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import projeto_fabricante_equipamento.n.DB.FabricanteDB;
import projeto_fabricante_equipamento.n.DB.EquipamentoDB;
import projeto_fabricante_equipamento.n.MODEL.Equipamento;
import projeto_fabricante_equipamento.n.MODEL.Fabricante;

/**
 *
 * @author vitor
 */
public class CadastrarEquipamentoIF extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarEquipamentoIF
     */
    public CadastrarEquipamentoIF() {
        initComponents();
        loadFabricantesCombo();
    }
    
    
    public void loadFabricantesCombo() {
        FabricanteDB fabricanteDB = new FabricanteDB();
        ArrayList<Fabricante> fabricantes = fabricanteDB.getFabricantes();
        
        for(int i=0; i< fabricantes.size(); i++){
            Fabricante fabricante = (Fabricante) fabricantes.get(i);
            fabricante_combo.addItem(fabricante);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nome_text = new javax.swing.JTextField();
        preco_text = new javax.swing.JTextField();
        cadastrar_bt = new javax.swing.JButton();
        fechar_bt = new javax.swing.JButton();
        fabricante_combo = new javax.swing.JComboBox<>();

        setClosable(true);
        setResizable(true);
        setTitle("Cadastrar Equipamento");

        jLabel1.setText("Fabricante:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Preço:");

        cadastrar_bt.setText("Cadastrar");
        cadastrar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_btActionPerformed(evt);
            }
        });

        fechar_bt.setText("Fechar");
        fechar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechar_btActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(45, 45, 45)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nome_text)
                            .addComponent(fabricante_combo, 0, 283, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cadastrar_bt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fechar_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(preco_text, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fabricante_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nome_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(preco_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechar_bt)
                    .addComponent(cadastrar_bt))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fechar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechar_btActionPerformed
        this.dispose();
    }//GEN-LAST:event_fechar_btActionPerformed

    private void cadastrar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_btActionPerformed
        if(nome_text.getText().isEmpty() || preco_text.getText().isEmpty() || fabricante_combo.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(rootPane, "Por favor, preencha os todos os campos!");
            return;
        } else{
            Fabricante fabricante = (Fabricante) fabricante_combo.getSelectedItem();
            Equipamento equipamento = new Equipamento(fabricante.getIdFabricante(),nome_text.getText(), Float.parseFloat(preco_text.getText()));
            EquipamentoDB equipamentoDB = new EquipamentoDB();
            boolean res = equipamentoDB.insert(equipamento);
            if(res){
                JOptionPane.showMessageDialog(this,"Equipamento cadastrado com sucesso!");
                nome_text.setText("");
                preco_text.setText("");
                fabricante_combo.setSelectedIndex(-1);
            }
            
        }
        
    }//GEN-LAST:event_cadastrar_btActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar_bt;
    private javax.swing.JComboBox<Fabricante> fabricante_combo;
    private javax.swing.JButton fechar_bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nome_text;
    private javax.swing.JTextField preco_text;
    // End of variables declaration//GEN-END:variables
}
