/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */

package projeto_fabricante_equipamento.n.GUI;

/**
 *
 * @author vitor
 */
public class MDIApplication extends javax.swing.JFrame {

    /** Creates new form MDIApplication */
    public MDIApplication() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        cadastrar_menu = new javax.swing.JMenu();
        cadastrar_fab = new javax.swing.JMenuItem();
        cadastrar_equip = new javax.swing.JMenuItem();
        editar_menu = new javax.swing.JMenu();
        editar_fab = new javax.swing.JMenuItem();
        editar_equip = new javax.swing.JMenuItem();
        remover_menu = new javax.swing.JMenu();
        remover_fab = new javax.swing.JMenuItem();
        remover_equip = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastrar_menu.setMnemonic('f');
        cadastrar_menu.setText("Cadastrar");

        cadastrar_fab.setMnemonic('o');
        cadastrar_fab.setText("Fabricante");
        cadastrar_fab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_fabActionPerformed(evt);
            }
        });
        cadastrar_menu.add(cadastrar_fab);

        cadastrar_equip.setMnemonic('s');
        cadastrar_equip.setText("Equipamento");
        cadastrar_equip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_equipActionPerformed(evt);
            }
        });
        cadastrar_menu.add(cadastrar_equip);

        menuBar.add(cadastrar_menu);

        editar_menu.setText("Editar");

        editar_fab.setMnemonic('o');
        editar_fab.setText("Fabricante");
        editar_fab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_fabActionPerformed(evt);
            }
        });
        editar_menu.add(editar_fab);

        editar_equip.setMnemonic('s');
        editar_equip.setText("Equipamento");
        editar_equip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_equipActionPerformed(evt);
            }
        });
        editar_menu.add(editar_equip);

        menuBar.add(editar_menu);

        remover_menu.setMnemonic('h');
        remover_menu.setText("Remover");

        remover_fab.setMnemonic('o');
        remover_fab.setText("Fabricante");
        remover_fab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remover_fabActionPerformed(evt);
            }
        });
        remover_menu.add(remover_fab);

        remover_equip.setMnemonic('s');
        remover_equip.setText("Equipamento");
        remover_equip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remover_equipActionPerformed(evt);
            }
        });
        remover_menu.add(remover_equip);

        menuBar.add(remover_menu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar_fabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_fabActionPerformed
        CadastrarFabricanteIF cadastrarfabricanteIF = new CadastrarFabricanteIF();
        desktopPane.add(cadastrarfabricanteIF);
        cadastrarfabricanteIF.setVisible(true);
    }//GEN-LAST:event_cadastrar_fabActionPerformed

    private void editar_fabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_fabActionPerformed
        EditarFabricanteIF editarfabricanteIF = new EditarFabricanteIF();
        desktopPane.add(editarfabricanteIF);
        editarfabricanteIF.setVisible(true);
    }//GEN-LAST:event_editar_fabActionPerformed

    private void remover_fabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remover_fabActionPerformed
        RemoverFabricanteIF removerfabricanteIF = new RemoverFabricanteIF();
        desktopPane.add(removerfabricanteIF);
        removerfabricanteIF.setVisible(true);
    }//GEN-LAST:event_remover_fabActionPerformed

    private void cadastrar_equipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_equipActionPerformed
        CadastrarEquipamentoIF cadastrarequipamentoIF = new CadastrarEquipamentoIF();
        desktopPane.add(cadastrarequipamentoIF);
        cadastrarequipamentoIF.setVisible(true);
    }//GEN-LAST:event_cadastrar_equipActionPerformed

    private void editar_equipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_equipActionPerformed
        EditarEquipamentoIF editarequipamentoIF = new EditarEquipamentoIF();
        desktopPane.add(editarequipamentoIF);
        editarequipamentoIF.setVisible(true);
    }//GEN-LAST:event_editar_equipActionPerformed

    private void remover_equipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remover_equipActionPerformed
        RemoverEquipamentoIF removerequipamentoIF = new RemoverEquipamentoIF();
        desktopPane.add(removerequipamentoIF);
        removerequipamentoIF.setVisible(true);
    }//GEN-LAST:event_remover_equipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrar_equip;
    private javax.swing.JMenuItem cadastrar_fab;
    private javax.swing.JMenu cadastrar_menu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem editar_equip;
    private javax.swing.JMenuItem editar_fab;
    private javax.swing.JMenu editar_menu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem remover_equip;
    private javax.swing.JMenuItem remover_fab;
    private javax.swing.JMenu remover_menu;
    // End of variables declaration//GEN-END:variables

}
