/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package projeto_fabricante_equipamento.n.GUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projeto_fabricante_equipamento.n.DB.EquipamentoDB;
import projeto_fabricante_equipamento.n.MODEL.Equipamento;

/**
 *
 * @author vitor
 */
public class RemoverEquipamentoIF extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modelTableEquipamentos = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int colunm){
            return false;
        }  
    };
    
    /**
     * Creates new form RemoverEquipamentoIF
     */
    public RemoverEquipamentoIF() {
        initComponents();
        loadEquipamentosTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        equip_table = new javax.swing.JTable();
        remover_bt = new javax.swing.JButton();
        fechar_bt = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Remover Equipamento");

        equip_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(equip_table);

        remover_bt.setText("Remover");
        remover_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remover_btActionPerformed(evt);
            }
        });

        fechar_bt.setText("Fechar");
        fechar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechar_btActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(remover_bt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(fechar_bt)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechar_bt)
                    .addComponent(remover_bt))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fechar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechar_btActionPerformed
        this.dispose();
    }//GEN-LAST:event_fechar_btActionPerformed

    private void remover_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remover_btActionPerformed
        int linhaSelecionadaEquipamentos = equip_table.getSelectedRow();
        int idEquipamento = (int) equip_table.getValueAt(linhaSelecionadaEquipamentos, 0);
       
        EquipamentoDB equipamentoDB = new EquipamentoDB();
        boolean res = equipamentoDB.delete(idEquipamento);
        if(res){
            JOptionPane.showMessageDialog(rootPane, "Equipamento removido com sucesso!");
            modelTableEquipamentos.removeRow(linhaSelecionadaEquipamentos);
            equip_table.setModel(modelTableEquipamentos);
            jScrollPane1.setViewportView(equip_table);
        }
    }//GEN-LAST:event_remover_btActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable equip_table;
    private javax.swing.JButton fechar_bt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton remover_bt;
    // End of variables declaration//GEN-END:variables

    private void loadEquipamentosTable() {
        modelTableEquipamentos.addColumn("idEquipamento");
        modelTableEquipamentos.addColumn("idFabricante");
        modelTableEquipamentos.addColumn("nome");
        modelTableEquipamentos.addColumn("preco");

        EquipamentoDB equipamentoDB = new EquipamentoDB();
        ArrayList<Equipamento> equipamentos = equipamentoDB.getEquipamentos();
        
        for(int i=0; i< equipamentos.size(); i++){
            Equipamento equipamento = (Equipamento) equipamentos.get(i);
            modelTableEquipamentos.addRow(new Object[]{
                equipamento.getIdEquipamento(), equipamento.getIdFabricante(), 
                equipamento.getNome(), equipamento.getPreco()
            });
        }
        equip_table.setModel(modelTableEquipamentos);
        jScrollPane1.setViewportView(equip_table);
    }
    
}
